### PR TITLE
Add @IsInt validation to hours per sprint

### LINKED ISSUE #47: Modify Directory API endpoint to only allow whole numbers in hrsPerSprint
Use validation decorator @isInt() from ValidationPipe in nest.js.

### PR DESCRIPTION
**Pull request by jenny-alexander**
# Description

Return error if user attempts to enter a number with decimals.

## Issue link

Fixes #47 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

I executed PATCH endpoint /teams/3/members/cceec61e-e3dc-4740-ac8b-dbeff70e97e6 _locally via Swagger_ and passed 10.5 as hours and error was returned.

**BEFORE FIX:** I can enter 10.5 hours and return code 200 is returned.
Screenshot 2023-11-09 at 12 39 16 PM

**AFTER FIX:** I try to enter 10.5 hours and error response code 400 is returned.
Screenshot 2023-11-09 at 12 51 01 PM

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by cherylli** [comment]
probably need to update the seed data too as i've put decimals in there 😂

**Comment by jenny-alexander** [comment]
Oh right! I'll check the seed file tomorrow and adjust it and add to this PR. Good catch.

**Review by curtwl — APPROVED** [review]
LGTM, tested with Swagger and got the 400 error with hrPerSprint = 5.6.

**Comment by jenny-alexander** [comment]
- Removed decimal hours from seed data.
- Added trailing commas to seed file (to keep formatting inline with prettier reqs).

**Review by kennytram — APPROVED** [review]
lgtm

**Review by cherylli — APPROVED** [review]
looks good. I guess prettier has not been formatting these files 🤔

**Pull request merged**
