### PR TITLE
Feature: ideation/projectIdea selection

### PR DESCRIPTION
**Pull request by JoshuaHinman**
# Description

This PR allows a voyage team member to choose one of their team's ideations as the final selection for their voyage.
Two new routes are added:
`/voyages/teams/{teamId}/ideations/{ideationId}/select`
`/voyages/teams/{teamId}/ideations/reset-selection`
Note: The name "ideations" refers to the projectIdeas model

There is a database migration, which adds the value `isSelected` to the projectIdeas schema.  Your local DB will need to be updated for this change

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Feature updates / changes
- [ ] Tests
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Migrate:
`npx prisma migrate dev`
`npx prisma db push`
Test:
`yarn test:e2e ideations`
`yarn test`

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have updated the change log

### CODE REVIEW

**Review by timDeHof — DISMISSED** [review]
Looks great! All the tests pass!

**Review by cherylli — COMMENTED** [review]
the actual responses and sample responses do not match in both endpoints, maybe you need to make a new response structure instead of using the ideationVote one
image
image


Another thing is the TeamId param doesn't seem to be doing anything, it works even if I put teamId = 55.

I think we need it for OWN_TEAM permission but we probably need another OWN_RESOURCE permission for future (https://app.clickup.com/t/86azr0q42)

Should we remove it for now to avoid possible confusion from the frontend team?

**Comment by JoshuaHinman** [comment]
> I think we need it for OWN_TEAM permission but we probably need another OWN_RESOURCE permission for future

Yes I did notice this issue - teamId is used to verify OWN_TEAM, but there is no check that the ideation is for that team.  Also, the projectIdea schema only references the teamMember that created it, not the team.  Should I add a function that checks this?

**Comment by cherylli** [comment]
> > I think we need it for OWN_TEAM permission but we probably need another OWN_RESOURCE permission for future
> 
> Yes I did notice this issue - teamId is used to verify OWN_TEAM, but there is no check that the ideation is for that team. Also, the projectIdea schema only references the teamMember that created it, not the team. Should I add a function that checks this?

yeah because teamMember is linked to a voyage team, so there's no need to have a "voyageTeam" linked to ideation. If it's not too much work, sure. Otherwise, we can just put a note in the code, and leave it till we add something like OWN_RESOURCE permission. I think all the other endpoints in ideation have the same issue anyway

**Review by cherylli — APPROVED** [review]
Perfect, thanks! I should have the CASL setup ready soon, then we can add all the permissions properly

**Comment by cherylli** [comment]
@timDeHof @curtwl this is ready for review again 🙏

**Review by curtwl — APPROVED** [review]
LGTM

**Review by timDeHof — CHANGES_REQUESTED** [review]
After running `yarn migrate:test:docker` and `yarn push:test:docker`, I ran into couple of errors. First, when I run `yarn seed`, I get the following error: 
Screenshot 2024-04-24 at 7 15 47 PM
Its seems that `isSelected` column in `VoyageTeamMember` model

The second error I encountered was when I ran `yarn test:e2e:docker` and I got the following error: 
Screenshot 2024-04-24 at 7 16 06 PM
its seems the tests are missing login step

**Comment by cherylli** [comment]
I also get the tests failed (forgot to run the tests again after the updates) but seeding is fine for me

**Comment by JoshuaHinman** [comment]
> I also get the tests failed (forgot to run the tests again after the updates) but seeding is fine for me

I ran the tests again and they work for me... the two routes that aren't working each call a loginAdmin() function that logs in as {
                email: "jessica.williamson@gmail.com",
                password: "password",
            }
Not sure why it would only work for me

**Comment by JoshuaHinman** [comment]
> After running `yarn migrate:test:docker` and `yarn push:test:docker`, I ran into couple of errors. First, when I run `yarn seed`, I get the following error:
 Its seems that `isSelected` column in `VoyageTeamMember` model
> 
> The second error I encountered was when I ran `yarn test:e2e:docker` and I got the following error: its seems the tests are missing login step

Ok I'm trying to figure out what's going on here-
I checked on my end, and there is no column `isSelected` in `voyageTeamMember`.  I've seen seeding errors like this when the DB has not migrated as intended.  It is working for me, using yarn migrate and yarn push.

The two tests, shown failing in the image, are the only ones that login as admin Jessica Williamson.  It looks like the login request is returning unauthorized for some reason.  It is working for me, so I'm not sure what the difference is.

Thank you for posting the screenshots - they are helpful!

**Comment by curtwl** [comment]
It's still working fine for me too
image

**Comment by timDeHof** [comment]
Ok, I ran `yarn migrate` and `yarn push` in Docker then ran `yarn:e2e:docker` and everything passed. I even ran their counterparts and everything passed. 

So I'm going to approve these changes...

**Review by timDeHof — APPROVED** [review]

**Pull request merged**
