### PR TITLE
Update docker compose to use timescaledb

### PR DESCRIPTION
**Pull request by cherylli**
# Description

Update docker compose to use Timescaledb/pg16 - which allows backup/restore between deployed db on railway 

## Issue link

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Feature updates / changes
- [ ] Tests
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

`yarn docker --build`, `yarn push`, `yarn seed` everything ran fine, checked on swagger as well

# Checklist:

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have updated the change log

### CODE REVIEW

**Review by JoshuaHinman — APPROVED** [review]
Update went smoothly, tests passed, swagger works

**Comment by curtwl** [comment]
All the update commands ran fine, but I'm getting this error from yarn test, is there something I need to re-configure?
image

**Comment by cherylli** [comment]
> All the update commands ran fine, but I'm getting this error from yarn test, is there something I need to re-configure? image

@curtwl 
I don't think so. I tried it again

1. `yarn docker`, maybe try `yarh docker --build` to rebuild the containers
2. `yarn push:test:docker` - to push the schema to the test db (but it shouldn't be required as db data is saved in a docker volume
3. `yarn test:docker` in docker, all pass
4. `yarn test` from outside docker, all pass

I noticed you used `yarn test` was that inside or outside docker?

**Comment by curtwl** [comment]
> @curtwl I don't think so. I tried it again
> 
> 1. `yarn docker`, maybe try `yarh docker --build` to rebuild the containers
> 2. `yarn push:test:docker` - to push the schema to the test db (but it shouldn't be required as db data is saved in a docker volume
> 3. `yarn test:docker` in docker, all pass
> 4. `yarn test` from outside docker, all pass
> 
> I noticed you used `yarn test` was that inside or outside docker?

I only tried inside Docker. Supabase stopped working for me and I hadn't bothered to figured out why, but I'm gonna have to because completely unrelated to this, my Docker uninstalled itself when I let the desktop app update itself. Reinstalling fails too. Welp, time to get reading SO threads...

**Comment by cherylli** [comment]
> > @curtwl I don't think so. I tried it again
> > 
> > 1. `yarn docker`, maybe try `yarh docker --build` to rebuild the containers
> > 2. `yarn push:test:docker` - to push the schema to the test db (but it shouldn't be required as db data is saved in a docker volume
> > 3. `yarn test:docker` in docker, all pass
> > 4. `yarn test` from outside docker, all pass
> > 
> > I noticed you used `yarn test` was that inside or outside docker?
> 
> @cherylli I only tried inside Docker. Supabase stopped working for me and I hadn't bothered to figured out why, but I'm gonna have to because completely unrelated to this, my Docker uninstalled itself when I let the desktop app update itself. Reinstalling fails too. Welp, time to get reading SO threads...

@curtwl if running tests inside docker you'll have to use `yarn test:docker` the reason is the test db has a different connection string but I couldn't setup docker to use different env files based on NODE_ENV

**Comment by timDeHof** [comment]
I tried to run the command 'yarn seed' after a migrate and got the following errors: 
Screenshot 2024-09-30 at 10 15 01 PM

**Comment by cherylli** [comment]
> I tried to run the command 'yarn seed' after a migrate and got the following errors: 
> Screenshot 2024-09-30 at 10 15 01 PM
> 
Did you push the schema to the right database? Npx prisma db push

**Comment by timDeHof** [comment]
> > I tried to run the command 'yarn seed' after a migrate and got the following errors:
> > Screenshot 2024-09-30 at 10 15 01 PM
> 
> Did you push the schema to the right database? Npx prisma db push

oops, i didn't pushed to the right database.seeding and all tests work now

**Review by curtwl — DISMISSED** [review]
All tests passing and setup working correctly on a fresh install on another machine
(my main device is still having problems)

**Comment by cherylli** [comment]
reassigned to @timDeHof as Josh is away

**Comment by cherylli** [comment]
@curtwl @curtwl_ review stale (resolved changelog conflict)

**Review by curtwl — APPROVED** [review]

**Review by timDeHof — APPROVED** [review]
Everything looks good! All tests passed and swagger works. Also both postgres databases had the correct image on them

**Pull request merged**
