### PR TITLE
Delete ideation vote and ideation

### PR DESCRIPTION
**Pull request by JoshuaHinman**
# Description

This PR updates the DELETE `voyages/teams/{teamId}/ideations/{ideationId}/ideation-votes` route to also delete the corresponding ideation, if there are no more votes for it.

Notes:
Functions `deleteIdeation` and `deleteIdeationVote` have been refactored to avoid conflicting with each other 
Upated e2e tests to check deletion of ideation when last vote is deleted
Fixed conflicts with other tests

## Issue link

Fixes # [86b0fw6kn](https://app.clickup.com/t/86b0fw6kn)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Feature updates / changes
- [x] Tests
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

In swagger: Login, post vote for team 1, ideation 1
In Prisma Studio: delete original projectIdeaVote (id: 1)
In Swagger: delete vote for team 1, ideation 1
Check results in Studio: no projectIdeaVotes for 1 , no projectIdea 1

Tests:
`yarn test:e2e ideations`

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have updated the change log

### CODE REVIEW

**Review by timDeHof — CHANGES_REQUESTED** [review]
Great job, all the e2e testing passed and but the unit tests failed for `ideations.service.spec.ts` on line 252. could you look into it?

**Review by timDeHof — CHANGES_REQUESTED** [review]
All the E2E test pass for ideation but I still getting a failure for the `ideations.service.spec.ts` on line 252. I think the issue is that you are comparing the `result` object to the `ideationVoteOne` object, which the later has `projectIdeaId` and the 'result` has just `id`. I think  checking if these ids are equal would pass the unit tests.

**Comment by cherylli** [comment]
They are working for me
image

**Review by timDeHof — APPROVED** [review]
ok, since the unit tests worked for @cherylli. I'll say it a pass then. but it does seem to be updated with `dev` branch.

**Review by cherylli — APPROVED** [review]
merged dev into the branch, rerun tests locally, all passed
also tested manually with swagger and works as expected 👍

**Pull request merged**
