### PR TITLE
Feature/populate voyage submission form

### PR DESCRIPTION
**Pull request by timDeHof**
# Description

This PR introduces a series of changes aimed at enhancing the codebase's maintainability, readability, and overall organization. Specifically, it focuses on the standardization of form titles and the introduction of a new form submission seed. Below is a summary of the key modifications and their impact on the project:

- Imported the `FormTitles` constants across various modules (`checkinform.ts`, `solo-project.ts`, `voyage-app.ts`, and forms) to replace hard-coded strings with constants. This will improve the readability and maintainability of the code by centralizing form titles in one location, while ensuring consistency across the application.

- Introduced a seed file `voyage-project-submission.ts` for the 'Voyage Project Submission form`. This file contains a `populateVoyageSubmissionForm` function that facilitates the creations and population of a new form in the database. This form is designed for submitting and sharing finished Chingu projects and includes fields for project details, experience feedback, and a rating scale for recommending Chingu to others

## Issue link

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Feature updates / changes
- [ ] Tests
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

run the script `yarn seed` to verify that there isn't any problems in the form that are using `FormTiltle`'s constants. Then run the usual unit and e2e tests.
# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have updated the change log

### CODE REVIEW

**Review by siasktv — DISMISSED** [review]
Looks all good and tests all passed!

**Comment by cherylli** [comment]
@siasktv did you run `prisma db seed` did it work for you?

**Comment by timDeHof** [comment]
> @siasktv did you run `prisma db seed` did it work for you?

Sorry, it was a mistake on my part. I didn't have the correct import path for `FormTitles` constants.I'll add testing for it in the PR description.

**Comment by cherylli** [comment]
I ran db seed but it wasn't populating the database I think the function wasn't called

**Comment by timDeHof** [comment]
> I ran db seed but it wasn't populating the database I think the function wasn't called

yes, sorry about that. I forgot to add it to the forms `index.ts` then there was typos in the seed form but its should be fixed now.

**Review by cherylli — APPROVED** [review]
rerun seed and database is populated properly now, all existing tests passed as well. Thanks!

**Review by JoshuaHinman — APPROVED** [review]
e2e and unit tests passed - looks good!

**Pull request merged**
