### PR TITLE
End of sprint 15 merge into main

### PR DESCRIPTION
**Pull request by cherylli**
# Description

End of sprint 15 merge into main

### CODE REVIEW

**Comment by cherylli** [comment]
Not sure why tests are broken, they are all fine locally. Will have a look after other more urgent tasks are done. Or if anyone has any idea, please post here 🙏

**Comment by timDeHof** [comment]
The tests pass locally for me too. It seems that the webhooks is finding a typescript error with 'req' variable in `ideations.service.spec.ts` and `ideations.controller.spec.ts`

**Comment by cherylli** [comment]
> I checkouted into the 'dev' branch and ran `yarn test`. The same tests are failing there too. It seems that there a typescript error with the `req` variable in `ideations.service.spec.ts` and `ideations.controller.spec.ts`.
> 
> Do you think it could be that CustomRequest interface is requiring the user object in the `req` variable to have 'email', 'roles', and 'voyageTeams' too?

i just pulled the latest dev branch and all tests passed 🤔

this is the existing code
```
export interface CustomRequest extends Request {
    user: {
        userId: string;
        email: string;
        roles: string[];
        voyageTeams: VoyageTeam[];
    };
}
```

**Comment by cherylli** [comment]
when it worked it was any, maybe I extended the wrong base class?
Hard to know what the issue is when i'm not getting errors locally. I wonder if it was node version 🤔

**Comment by timDeHof** [comment]
> when it worked it was any, maybe I extended the wrong base class? Hard to know what the issue is when i'm not getting errors locally. I wonder if it was node version 🤔

maybe. But here is what typescript is saying on my computer: 
```
Argument of type '{ user: { userId: string; }; }' is not assignable to parameter of type 'CustomRequest'.
  Type '{ user: { userId: string; }; }' is missing the following properties from type 'CustomRequest': cache, credentials, destination, headers, and 17 more.ts(2345)
  ```
  I think the issue is that its looking for variables that `Request` needs.

**Comment by cherylli** [comment]
> > when it worked it was any, maybe I extended the wrong base class? Hard to know what the issue is when i'm not getting errors locally. I wonder if it was node version 🤔
> 
> maybe. But here is what typescript is saying on my computer:
> 
> ```
> Argument of type '{ user: { userId: string; }; }' is not assignable to parameter of type 'CustomRequest'.
>   Type '{ user: { userId: string; }; }' is missing the following properties from type 'CustomRequest': cache, credentials, destination, headers, and 17 more.ts(2345)
> ```
> 
> I think the issue is that its looking for variables that `Request` needs.

yeah that's exactly what the github actions says. I don't know why i'm not getting error on my machine. WHat's your node version? Mine is `v21.6.1`

but if I extends Request, it should have everything in Request right?

**Comment by cherylli** [comment]
github actions using node 18. I might make a fork and try changing it

**Comment by cherylli** [comment]
nope node 21 in github actions doesn't work.

**Comment by timDeHof** [comment]
I have node version 20 on my computer

**Comment by cherylli** [comment]
I think maybe this - I didn't import {Request} from `express`
could you try this adding this to the `src/global/types/CustomRequest.ts` file so it looks like

```
import { Request } from "express";

type VoyageTeam = {
    teamId: number;
    memberId: number;
};

export interface CustomRequest extends Request {
    user: {
        userId: string;
        email: string;
        roles: string[];
        voyageTeams: VoyageTeam[];
    };
}

```

I tried that on my fork still fail though

image


compared to 

image

**Comment by timDeHof** [comment]
> I think maybe this - I didn't import {Request} from `express` could you try this adding this to the `src/global/types/CustomRequest.ts` file so it looks like
> 
> ```
> import { Request } from "express";
> 
> type VoyageTeam = {
>     teamId: number;
>     memberId: number;
> };
> 
> export interface CustomRequest extends Request {
>     user: {
>         userId: string;
>         email: string;
>         roles: string[];
>         voyageTeams: VoyageTeam[];
>     };
> }
> ```
> 
> I tried that on my fork still fail though
> 
> image
> 
> compared to
> 
> image

I tried that and got a similar error with `res` looking for alot more properties.
Screenshot 2024-03-23 at 11 15 30 AM

**Review by curtwl — APPROVED** [review]
all passed

**Review by timDeHof — APPROVED** [review]
looks ready!!! I have ran unit tests and e2e tests on dev branch and it passed.

**Pull request merged**
