### PR TITLE
Merge Dev branch into Main

### PR DESCRIPTION
**Pull request by jenny-alexander**
# Description

Merge Development branch into Main branch

### CODE REVIEW

**Comment by cherylli** [comment]
Probably need to wait till we merge Kenny's test PRs
image

this should be fixed in those PRs - e2e can't read absolute paths

**Comment by cherylli** [comment]
do we want to run the e2e tests on main as well?
looks like this only runs the unit tests

**Comment by kennytram** [comment]
> do we want to run the e2e tests on main as well? looks like this only runs the unit tests

We will need to set it up to work with the Test DB first before deciding to run e2e tests on the main.  I don't have access to this project's settings, so I wouldn't know if it is already configured or not.

**Comment by cherylli** [comment]
> > do we want to run the e2e tests on main as well? looks like this only runs the unit tests
> 
> We will need to set it up to work with the Test DB first before deciding to run e2e tests on main. I don't have access to this project's settings, so I wouldn't know if it is already configured or not.

what do you need? is it just the test `DATABASE_URL` github repo secret? If so, Jenny can set that up

**Review by cherylli — APPROVED** [review]

**Pull request merged**
