### PR TITLE
add 'postinstall' to enable hooks after install

### PR DESCRIPTION
**Pull request by kennytram**
# Description

Enable Git hooks for Husky immediately after `yarn install` [husky's doc](https://typicode.github.io/husky/getting-started.html#yarn-2) 

For current developers, please run `yarn husky install` to ensure that Husky functions correctly.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
- After `yarn husky install`
-- Intentionally made lint mistakes in some files after `yarn husky install`
-- Detected by Husky after push 

- Before `yarn husky install`
-- Intentionally made lint mistakes before `yarn husky install`
-- Not detected by Husky after push

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by cherylli** [comment]
not working for me 
image

**Comment by cherylli** [comment]
So I fixed it now and working, it's a windows issue (for me at least)

I followed this
https://github.com/typicode/husky/issues/850#issuecomment-774231951

**Comment by smurph7894** [comment]
Just fyi, husky does not work with Github Desktop but I am able to do it using gitbash.

**Review by smurph7894 — APPROVED** [review]
see FYI comment but otherwise is working for me.

**Comment by cherylli** [comment]
So current husky setup is not quite working for me, it goes like this,
I push, husky runs automatically, but the code BEFORE linting was pushed
so I had to do another commit for the formatted code

So the correct workflow should be 
1. issue push command
2. husky runs
3. push FORMATTED code

is this happening to anyone else? I haven't looked it up yet but I was wondering if it was just me or not

**Comment by kennytram** [comment]
> So current husky setup is not quite working for me, it goes like this, I push, husky runs automatically, but the code BEFORE linting was pushed so I had to do another commit for the formatted code
> 
> So the correct workflow should be
> 
> 1. issue push command
> 2. husky runs
> 3. push FORMATTED code
> 
> is this happening to anyone else? I haven't looked it up yet but I was wondering if it was just me or not

It's what Dan wanted. Otherwise, "pre-commit would get too annoying" in his exact words.

**Comment by cherylli** [comment]
> What do you think?

that's basically what I have to do now, but manually, but we shouldn't have to make an extra commit to include husky changes

if you look at this as an example, I basically have to do 2 commits every time I push, and one just for the husky changes
https://github.com/chingu-x/chingu-dashboard-be/compare/dev...feature/sprints-endpoints

Is there any reason we can't use a pre commit hook? I've used pre commit hooks for format in all my other projects and no issues

**Comment by kennytram** [comment]
> 
> 
> > What do you think?
> 
> 
> 
> that's basically what I have to do now, but manually, but we shouldn't have to make an extra commit to include husky changes
> 
> 
> 
> if you look at this as an example, I basically have to do 2 commits every time I push, and one just for the husky changes
> 
> https://github.com/chingu-x/chingu-dashboard-be/compare/dev...feature/sprints-endpoints
> 
> 
> 
> Is there any reason we can't use a pre commit hook? I've used pre commit hooks for format in all my other projects and no issues
> 
> 

Dan doesn't like it 😄

"Pre-commit would get too annoying" in his exact words.

**Comment by cherylli** [comment]
> > > What do you think?
> > 
> > 
> > that's basically what I have to do now, but manually, but we shouldn't have to make an extra commit to include husky changes
> > if you look at this as an example, I basically have to do 2 commits every time I push, and one just for the husky changes
> > [dev...feature/sprints-endpoints](https://github.com/chingu-x/chingu-dashboard-be/compare/dev...feature/sprints-endpoints)
> > Is there any reason we can't use a pre commit hook? I've used pre commit hooks for format in all my other projects and no issues
> 
> Dan doesn't like it 😄
> 
> "Pre-commit would get too annoying" in his exact words.

he's not going to commit or push this repo much. double commits annoys me and clogging the commit history 😂

What does everyone else in the team think?

**Comment by kennytram** [comment]
> > > > What do you think?
> > > 
> > > 
> > > that's basically what I have to do now, but manually, but we shouldn't have to make an extra commit to include husky changes
> > > if you look at this as an example, I basically have to do 2 commits every time I push, and one just for the husky changes
> > > [dev...feature/sprints-endpoints](https://github.com/chingu-x/chingu-dashboard-be/compare/dev...feature/sprints-endpoints)
> > > Is there any reason we can't use a pre commit hook? I've used pre commit hooks for format in all my other projects and no issues
> > 
> > 
> > Dan doesn't like it 😄
> > "Pre-commit would get too annoying" in his exact words.
> 
> he's not going to commit or push this repo much. double commits annoys me and clogging the commit history 😂
> 
> What does everyone else in the team think?



> > > > What do you think?
> > > 
> > > 
> > > that's basically what I have to do now, but manually, but we shouldn't have to make an extra commit to include husky changes
> > > if you look at this as an example, I basically have to do 2 commits every time I push, and one just for the husky changes
> > > [dev...feature/sprints-endpoints](https://github.com/chingu-x/chingu-dashboard-be/compare/dev...feature/sprints-endpoints)
> > > Is there any reason we can't use a pre commit hook? I've used pre commit hooks for format in all my other projects and no issues
> > 
> > 
> > Dan doesn't like it 😄
> > "Pre-commit would get too annoying" in his exact words.
> 
> he's not going to commit or push this repo much. double commits annoys me and clogging the commit history 😂
> 
> What does everyone else in the team think?

`    "husky:format": "prettier --check \"src/**/*.ts\" \"test/**/*.ts\" || (git reset --soft HEAD~1 && yarn format && exit 1)"`

Would this work for you?

**Comment by kennytram** [comment]
> > > > What do you think?
> > > 
> > > 
> > > that's basically what I have to do now, but manually, but we shouldn't have to make an extra commit to include husky changes
> > > if you look at this as an example, I basically have to do 2 commits every time I push, and one just for the husky changes
> > > [dev...feature/sprints-endpoints](https://github.com/chingu-x/chingu-dashboard-be/compare/dev...feature/sprints-endpoints)
> > > Is there any reason we can't use a pre commit hook? I've used pre commit hooks for format in all my other projects and no issues
> > 
> > 
> > Dan doesn't like it 😄
> > "Pre-commit would get too annoying" in his exact words.
> 
> he's not going to commit or push this repo much. double commits annoys me and clogging the commit history 😂
> 
> What does everyone else in the team think?

Alright I just made another commit that would `git reset --soft HEAD~1 && exit 1` if there are format errors within staged files.

**Comment by jenny-alexander** [comment]
I haven't tried any of this yet - but agree that it should be a pre-commit hook and we shouldn't push two commits for this.
If we want to keep our git commit history clean"er", it's possible to do a git rebase.

**Comment by Dan-Y-Ko** [comment]
> > > > What do you think?
> > > 
> > > 
> > > that's basically what I have to do now, but manually, but we shouldn't have to make an extra commit to include husky changes
> > > if you look at this as an example, I basically have to do 2 commits every time I push, and one just for the husky changes
> > > [dev...feature/sprints-endpoints](https://github.com/chingu-x/chingu-dashboard-be/compare/dev...feature/sprints-endpoints)
> > > Is there any reason we can't use a pre commit hook? I've used pre commit hooks for format in all my other projects and no issues
> > 
> > 
> > Dan doesn't like it 😄
> > "Pre-commit would get too annoying" in his exact words.
> 
> he's not going to commit or push this repo much. double commits annoys me and clogging the commit history 😂
> 
> What does everyone else in the team think?

Pre-commit shouldn't change anything. There just seems to be something funky going on with the husky workflow. It's supposed to prevent a push if there's linting errors and format **before** the push. It's the same thing as a pre-commit, so if it works for pre-commit but not pre-push...there's something weird going on.

**Comment by Dan-Y-Ko** [comment]
> > What do you think?
> 
> that's basically what I have to do now, but manually, but we shouldn't have to make an extra commit to include husky changes
> 
> if you look at this as an example, I basically have to do 2 commits every time I push, and one just for the husky changes [dev...feature/sprints-endpoints](https://github.com/chingu-x/chingu-dashboard-be/compare/dev...feature/sprints-endpoints)
> 
> Is there any reason we can't use a pre commit hook? I've used pre commit hooks for format in all my other projects and no issues

If you use a pre commit hook, literally every time you try to commit, you will have to fix any linting errors. This honestly is a just a huge hassle. For me personally, I always do multiple commits and then when I'm done, I'll push it up to the repo and before I push, I do a lint/format. I like having the check in a pre-push in case I or someone else forgets to do that. Having to do 1 extra commit is way better tradeoff for me than having to fix stuff every time I commit (I'm not really sure what you mean about double commit, it should only be 1 extra). That being said that part is not relevant to the husky workflow issue and can be tweaked for each team. When I tried to set it up on the fe, it didn't matter what I used, it wasn't working for other people so yea.

**Review by cherylli — APPROVED** [review]
works for me, thanks for fixing this

**Review by jenny-alexander — APPROVED** [review]
It works for me after I set the pre-commit script to executable. Approved!

**Pull request merged**
