### PR TITLE
Feat: CASL permissions for features endpoint

### PR DESCRIPTION
**Pull request by Ajen07**
# Description

- Add new permissions for Team  Project Features endpoint

## Issue link

[Fixes # (issue)](https://app.clickup.com/t/86azr0q42)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Feature updates / changes
- [ ] Tests
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- test with yarn `test:docker`

- tested with swagger

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have updated the change log

### CODE REVIEW

**Review by timDeHof — CHANGES_REQUESTED** [review]
All the tests passed for unit and e2e tests. Also the features endpoints in swagger passed. one suggestion would be to have an example of a teamId or featureId for the endpoints that require them in swagger.

**Review by cherylli — APPROVED** [review]
changes look good and I've ran all the tests 🙌

**Comment by cherylli** [comment]
@timDeHof @JoshuaHinman @curtwl could any of you take a look at this PR? Thanks!

**Review by timDeHof — APPROVED** [review]
Looks great! every e2e and unit tests passed. Also in swagger, the feature endpoint passed with info and status code of 200.

**Pull request merged**
