### PR TITLE
Add github workflow for PR reminder

### PR DESCRIPTION
**Pull request by cherylli**
# Description

Add github workflow for PR reminder

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Feature updates / changes
- [ ] Tests
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

# Checklist:

- [] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have updated the change log

### CODE REVIEW

**Comment by curtwl** [comment]
Cron syntax looks good, ran the script locally with Act with no errors.

**Review by curtwl — APPROVED** [review]

**Comment by timDeHof** [comment]
@curtwl I would like to test it with Act too. But I'm getting an error saying "Error: Parameter token or opts.auth is required". I looked and saw it asking for a `GITHUB_TOKEN` secret. Did you have this too? If so, where did you find it?

**Review by timDeHof — COMMENTED** [review]
I couldn't get this action to do anything when used it in another repo. But the cron expression is correct. I'm just not sure how to get it to work.

**Comment by cherylli** [comment]
I added the same workflow to my fork and invited you two as an outside collaborator so I can request reviews.

then it should notify the reviewers 2 times a day

**Review by timDeHof — APPROVED** [review]
I just now got pinged in @cherylli's fork awhile. So it worked

**Review by timDeHof — APPROVED** [review]
I just now got pinged in @cherylli's fork awhile. So it worked

**Pull request merged**
