### PR TITLE
update regex in origin list

### PR DESCRIPTION
**Pull request by Dan-Y-Ko**
# Description

The regex for the preview deployments is wrong. Vercel generates dynamic preview urls that can have - in them, which isn't covered in the regex.

For example: chingu-dashboard-git-feature-refreshtoken-chingu-dashboard.vercel.app

the feature-refreshtoken part is dynamic with a - in between

As a result, there's a cors error when testing from the preview deployments on vercel

## Issue link

Fixes # (issue)

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] Feature updates / changes
- [ ] Tests
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Tested through vercel

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules
- [x] I have updated the change log

### CODE REVIEW

**Comment by Dan-Y-Ko** [comment]
Not sure how you want the changelog updated, if you do. Just let me know if you want me to do that and how

**Comment by cherylli** [comment]
You can just copy this format - https://github.com/chingu-x/chingu-dashboard-be/pull/205/files

**Comment by Dan-Y-Ko** [comment]
> You can just copy this format - https://github.com/chingu-x/chingu-dashboard-be/pull/205/files

I pushed the changelog update

**Comment by cherylli** [comment]
@Dan-Y-Ko you reformatted the whole file 😂
image

**Comment by Dan-Y-Ko** [comment]
let me know if that fixed it

**Comment by cherylli** [comment]
> > @Dan-Y-Ko you reformatted the whole file 😂 image
> 
> 🤔 All I did was copy the line and put it the change

Your IDE probably auto formatted it, I think it just added blank lines and removed extra spaces. I've also moved the change to the bottom

**Review by cherylli — APPROVED** [review]
thanks!

**Review by curtwl — APPROVED** [review]
lgtm

**Pull request merged**
