### PR TITLE
Update TechItemResponse ID in techs.response.ts

### PR DESCRIPTION
**Pull request by siasktv**
# Description

Updated the id to teamTechStackItemVoteId on TechItemResponse

## Issue link

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Feature updates / changes
- [ ] Tests
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Through Swagger response. 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have updated the change log

### CODE REVIEW

**Review by cherylli — COMMENTED** [review]
hmm i'm still seeing id..
image

**Review by cherylli — COMMENTED** [review]
I'm still seeing this, anyone else? 

image

I think you change the wrong thing? as I see the get endpoint service is updated

**Review by timDeHof — CHANGES_REQUESTED** [review]
This is what I get when running techs Controller e2e test.  it seems the test for getting all the data for the tech categories and items. 

Screenshot 2024-04-14 at 10 05 00 PM

**Comment by cherylli** [comment]
#138

**Pull request closed without merging**
