### PR TITLE
Chore/update sprints

### PR DESCRIPTION
**Pull request by curtwl**
# Description

Minor changes: 
- Updated /voyages/sprints by removing teamMeetings from the response of getSprintDatesByTeamId. 
- Added VoyageResponseWithoutMeetings and SprintWithoutMeetings to the API response definitions.

## Issue link

Fixes https://app.clickup.com/t/86azu18qn

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Feature updates / changes
- [ ] Tests
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have updated the change log

### CODE REVIEW

**Review by JoshuaHinman — DISMISSED** [review]
Changes look good - all tests passed!

**Review by cherylli — CHANGES_REQUESTED** [review]
I think you changed the wrong endpoint. It looks like you changed `voyages/sprints/teams/{teamId}` instead of `voyages/sprints` as per the task description.

**Review by cherylli — APPROVED** [review]
Thanks. It works as expected now. I like that you included the clickup link in the Issues section, maybe we should all start doing that

**Review by timDeHof — APPROVED** [review]
great job! All unit and e2e tests pass. running swagger and `GET /voyages/sprints` produced a response that doesn't have the `teamMeetings`.

**Pull request merged**
