### PR TITLE
Feature - tech stack endpoints

### PR DESCRIPTION
**Pull request by cherylli**
# Description

Added tech stack endpoints, with some required schema changes

### Techs 
GET 
`/api/v1/techs/team/{teamId}`
gets a list of techs with team vote data(all of them, both picked by the team and not)

POST
`/api/v1/techs/team/{teamId}/tech/{techId}/new`
add a new tech vote (new tech) - creates a new tech vote entry, and insert team/user id

POST
`/api/v1/techs/team/{teamId}/tech/{teamTechId}`
votes for a tech the team has already picked 

DELETE
`/api/v1/techs/team/{teamId}/tech/{teamTechId}`
removes a vote, also removes the entry from `teamTechStackItem` table if it was the only vote

### Users
GET
`/api/v1/users`
get all users (basic info)

GET
`/api/v1/users/{userId}`
get a user (detail with all voyage info)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

All endpoints have been tested with seed data, using Swagger at `http://localhost:8000/docs`
Tests have not been implemented. They will be added at a latest stage.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by cherylli** [comment]
There's a conflicting rule between eslint and prettier `src\techs\techs.controller.ts` 
eslint wants me to use double quote, and prettier wants me to use single quotes, I've tried backticks but it keeps reformatting it back to single quote when I run `yarn lint`
image

image
image

**Comment by awlFCCamp** [comment]
Tested all endpoints work as expected

**Review by jenny-alexander — APPROVED** [review]
Approved

**Comment by jenny-alexander** [comment]
[CGD-11 Feature - Tech Stack Endpoint](https://trello.com/c/pmAKM8Dj/2-cgd-11-feature-tech-stack-endpoint)

**Pull request merged**
