### PR TITLE
Update docker compose and localhost port

### PR DESCRIPTION
**Pull request by cherylli**
# Description

Making these changes so I can connect the solo project evaluation app to the backend docker from a docker container.

Having a named network also make it more flexible for other containers to connect to the existing backend containers

1. Update cors policy to allow any ports from localhost
2. Add `networks` settings to docker compose

https://docs.docker.com/compose/networking/#specify-custom-networks

## Issue link

N/A

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Feature updates / changes
- [ ] Tests
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Removed/deleted old docker containers and use `docker compose up` again to setup new containers.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have updated the change log

### CODE REVIEW

**Review by curtwl — DISMISSED** [review]
Looks good, successfully ran docker compose up

**Review by timDeHof — CHANGES_REQUESTED** [review]
looks good, I successfully ran the yarn command yarn docker:down and removed the docker container. I did notice that the command yarn docker doesn't work because the script runs docker-compose up -d instead of docker compose up -d. Changing to the later, fixed it and made the command yarn docker work again.

**Comment by cherylli** [comment]
> looks good, I successfully ran the yarn command yarn docker:down and removed the docker container. I did notice that the command yarn docker doesn't work because the script runs docker-compose up -d instead of docker compose up -d. Changing to the later, fixed it and made the command yarn docker work again.

This command actually worked for me. I didn't set this up, so I'm not sure, maybe it doesn't work for everyone, I'll change to the other one, but interested to know where this command come from

image

**Comment by timDeHof** [comment]
> > looks good, I successfully ran the yarn command yarn docker:down and removed the docker container. I did notice that the command yarn docker doesn't work because the script runs docker-compose up -d instead of docker compose up -d. Changing to the later, fixed it and made the command yarn docker work again.
> 
> This command actually worked for me. I didn't set this up, so I'm not sure, maybe it doesn't work for everyone, I'll change to the other one, but interested to know where this command come from
> 
> image
> 
> image
> 
> Maybe I should remove the "version" part too

I'm not too familiar with docker and its packages. But when I ran the command before changing it, I got `docker-compose: command not found`.
Screenshot 2024-09-13 at 10 51 06 PM
or maybe its a alias in zsh or something.

**Comment by cherylli** [comment]
I found this fyi, it looks like `docker-compose` comes with v1. I must have a really old docker installation probably like over 5 years

https://kodekloud.com/blog/docker-compose-command-not-found/

I changed it to `docker compose` and removed `version`

**Review by timDeHof — APPROVED** [review]
Looks good, All scripts work now!

**Review by curtwl — APPROVED** [review]

**Pull request merged**
