### PR TITLE
Refractor: update all form title reference

### PR DESCRIPTION
**Pull request by Ajen07**
# Description

All the form title reference are updated to use  the values in the file formTitle.ts
## Issue link

https://app.clickup.com/t/86azvdyff

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Feature updates / changes
- [ ] Tests
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- Performed unit tests
tests passed

- Performed  e2e tests
passed

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have updated the change log

### CODE REVIEW

**Review by timDeHof — APPROVED** [review]
Looks great to me! every test passed for me

**Review by cherylli — CHANGES_REQUESTED** [review]
All tests passed but seeding fail probably because baseUrl doesn't apply to prisma, so prisma can't find `FormTitles` in `"src/global/constants/formTitles"`

image

**Review by cherylli — APPROVED** [review]
thanks for the quick fix, prisma db seed is working now and all tests passed

**Review by cherylli — APPROVED** [review]

**Review by curtwl — APPROVED** [review]
Looks good!

**Pull request merged**
