### PR TITLE
refactor: changed E2E import paths to use '@/' 

### PR DESCRIPTION
**Pull request by timDeHof**
# Description

The import paths are changed to use the alias '@/' instead of relative paths. This improves code readability and maintainability by making it easier to understand the structure of the project and reducing the complexity of navigating through nested directories.

## Issue link

Fixes [Make e2e imports (and other imports) work with paths/absolute inputs](https://app.clickup.com/t/86b2346xp)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Feature updates / changes
- [ ] Tests
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

You test this PR by running the command `yarn test:e2e` or `yarn test:e2e:docker`, which all tests should pass.

If we want I could work adding absolute paths to the unit tests too. Let me know in the comments.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [ ] I have updated the change log

### CODE REVIEW

**Review by cherylli — CHANGES_REQUESTED** [review]
Everything works, but missing changelog 😊

**Comment by timDeHof** [comment]
> Everything works, but missing changelog 😊

oops, sorry. I will do it now. but where should it be under? unreleased?

**Comment by cherylli** [comment]
> > Everything works, but missing changelog 😊
> 
> oops, sorry. I will do it now. but where should it be under? unreleased?

yes, unreleased please, then when I do another merge to main I'll move them to a new releast section, and restart the "unreleased" section

**Review by cherylli — APPROVED** [review]

**Review by JoshuaHinman — APPROVED** [review]
All tests passed!

**Pull request merged**
