### PR TITLE
Update response Ids - POST voyages/teams/teamId/techs

### PR DESCRIPTION
**Pull request by timDeHof**
# Description

This PR will rename the id property in the TechItemResponse class to teamTechStackItemVoteId to provide better clarity and improve semantics. The example value for the teamMemberId property has been updated to 8 to maintain consistency with other example values. The create method in the TechsService class now returns an object that includes the teamTechStackItemVoteId property for consistency. Similarly, the delete method now returns an object that includes the teamTechStackItemVoteId property for consistency.

## Issue link

Fixes # [https://app.clickup.com/t/86azw0fjm](https://app.clickup.com/t/86azw0fjm)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Feature updates / changes
- [ ] Tests
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

In swagger:

1. run `POST /api/v1/auth/login`
2. After a successful login, run `POST /api/v1/voyages/teams/{teamId}/techs/{teamTechId}` with 'teamId: 2' and 'teamTechId: 6'. I found these two parameters worked, as the example parameters gave some errors. 
The response body should be a success like the picture below:
Screenshot 2024-04-19 at 5 33 20 PM

3. After voting on a tech, run `DELETE /api/v1/voyages/teams/{teamId}/techs/{teamTechId}` with the same parameters previous used. 
The response body should be a success like the picture below:
Screenshot 2024-04-19 at 5 33 46 PM

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have updated the change log

### CODE REVIEW

**Review by cherylli — DISMISSED** [review]
Everything works fine - I think we should add a more descriptive error message when we have an invalid Id, since there's no teamTechId = 11, and maybe also update the sample input? (you can add to this PR or I can write another task for this) 

image

**Comment by timDeHof** [comment]
Yes, I will do that. I was getting same the error when I started this task and was a little confusing which was making me think it was another issue.

**Comment by timDeHof** [comment]
I have updated the example parameters in `POST /api/v1/voyages/teams/{teamId}/techs/{teamTechId}` and `DELETE /api/v1/voyages/teams/{teamId}/techs/{teamTechId}` to provide an accurate output.

**Comment by timDeHof** [comment]
I have added error handling that would check if the team tech stack id is present since the message that is shown from bad request response isn't very descriptive.

**Review by cherylli — CHANGES_REQUESTED** [review]
I just realize the original task is to update `POST voyages/teams/teamId/techs` but it seems `POST voyages/teams/teamId/techs/{teamTechId} is updated here

Although I think all techs vote related endpoints would require update anyway

In `POST voyages/teams/teamId/techs` it automatically adds a vote as well, you can verify the ID in the database

**Review by cherylli — CHANGES_REQUESTED** [review]
thanks, everything was working with manual test on swagger but e2e tests are failing now due to the response updates

image

**Comment by timDeHof** [comment]
I fixed the tests that were failing and add a new test that checks if a tech stack item is deleted from the database if its last vote was deleted.

**Review by cherylli — APPROVED** [review]
everything work fine, all tests passed

**Review by JoshuaHinman — APPROVED** [review]
Looks good - it worked as described

**Pull request merged**
